#!/bin/bash
FILE=proceso3

if [[ ! -d bin ]]; then
    mkdir bin
fi
make bin/$FILE

if [[ ! -e cfg/$FILE.log ]]; then
    mkdir cfg
    touch cfg/$FILE.log
fi

if test -f "./bin/$FILE"; then
    ./bin/$FILE
fi