#!/bin/bash
FILE=proceso3
make $FILE
if [[ ! -e cfg/$FILE.log ]]; then
    mkdir cfg
    touch cfg/$FILE.log
fi
if test -f "./$FILE"; then
    valgrind --tool=memcheck --leak-check=yes --show-possibly-lost=no --show-reachable=no --num-callers=20 ./$FILE
fi